DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS posts (
	id INT PRIMARY KEY AUTO_INCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL,
	slug TEXT NOT NULL,
	content TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50),
	email VARCHAR(255),
	password VARCHAR(255),
	is_approved TINYINT(1)
) ENGINE=InnoDB;