DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS users;

CREATE TABLE pages (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title TEXT NOT NULL,
	slug TEXT NOT NULL,
	content TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE posts (
	id INT PRIMARY KEY AUTO_INCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL,
	slug TEXT NOT NULL,
	content TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE users (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50),
	email VARCHAR(100),
	password VARCHAR(255),
	is_approved BOOLEAN,
	role VARCHAR(50) DEFAULT 'user'
) ENGINE=InnoDB;